// What depends on the production address: the canonical link and social image
// URLs in index.html, robots.txt, and sitemap.xml. Shared by
// generate-site.mjs (writes them) and validate-site.mjs (checks them).

export const SHARE_IMAGE_PATH = "assets/share-card.png";
export const SHARE_IMAGE_SIZE = { width: 1200, height: 630 };
const SHARE_IMAGE_ALT = "LiD Test Prep: Prepare with clarity. Pass with confidence.";
const INDENT = "    ";
const BLOCK_PATTERN = /[ \t]*<!-- site:start[\s\S]*?<!-- site:end -->/;

// A usable origin is an https URL with no query or fragment that ends in "/".
export function validateOrigin(origin) {
  if (!origin) return null;
  let url;
  try {
    url = new URL(origin);
  } catch {
    return `"${origin}" is not a URL.`;
  }
  if (url.protocol !== "https:") return "The origin must start with https://.";
  if (url.search || url.hash) return "The origin must not have a query or fragment.";
  if (!origin.endsWith("/")) return 'The origin must end with "/".';
  if (url.href !== origin) return `Write the origin as ${url.href}.`;
  return null;
}

const escapeAttribute = (value) => value.replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;");

// Without an origin the image URLs stay relative, which works for the app
// itself but not for social crawlers, so the validator treats that as unfinished.
export function renderHeadBlock(origin) {
  const image = escapeAttribute(origin ? `${origin}${SHARE_IMAGE_PATH}` : SHARE_IMAGE_PATH);
  const lines = [];
  if (origin) {
    lines.push(`<link rel="canonical" href="${escapeAttribute(origin)}">`);
    lines.push(`<meta property="og:url" content="${escapeAttribute(origin)}">`);
  }
  lines.push(
    `<meta property="og:image" content="${image}">`,
    '<meta property="og:image:type" content="image/png">',
    `<meta property="og:image:width" content="${SHARE_IMAGE_SIZE.width}">`,
    `<meta property="og:image:height" content="${SHARE_IMAGE_SIZE.height}">`,
    `<meta property="og:image:alt" content="${SHARE_IMAGE_ALT}">`,
    `<meta name="twitter:image" content="${image}">`,
    `<meta name="twitter:image:alt" content="${SHARE_IMAGE_ALT}">`
  );
  return [
    `${INDENT}<!-- site:start generated by scripts/generate-site.mjs from site-config.js; do not edit by hand -->`,
    ...lines.map((line) => `${INDENT}${line}`),
    `${INDENT}<!-- site:end -->`
  ].join("\n");
}

export function readHeadBlock(html) {
  return html.match(BLOCK_PATTERN)?.[0] ?? null;
}

export function applyHeadBlock(html, block) {
  if (!BLOCK_PATTERN.test(html)) throw new Error("index.html has no <!-- site:start --> ... <!-- site:end --> block");
  return html.replace(BLOCK_PATTERN, () => block);
}

export function renderRobots(origin) {
  return `User-agent: *\nAllow: /\n\nSitemap: ${origin}sitemap.xml\n`;
}

export function renderSitemap(origin) {
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    "  <url>",
    `    <loc>${origin.replace(/&/g, "&amp;")}</loc>`,
    "  </url>",
    "</urlset>",
    ""
  ].join("\n");
}

// Crawlers read robots.txt only at the root of a host.
export function robotsIsReachable(origin) {
  return new URL(origin).pathname === "/";
}
